import Navbar from "@/components/Navbar";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Providers } from "./providers";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

export const metadata = {
  title: "File Management System",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <Providers session={session}>
          {session && <Navbar />}
          <div className="flex">
            <div>{session && <Sidebar />}</div>
            <div className="container m-10">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
